add chi library
alexander1389/metrics pull request #5
Opened 2022-07-17 19:09 UTC by alexander1389

2022-07-19 19:33 UTC, capsulated requested changes
Одну ошибку обязательно исправить с конфликтом импорта.

Насчёт интерфейса - сделать, как удобнее, но запомнить стандартный подход, чтобы знать)

В остальном, всё отлично, хорошо структурированный и чистый код.

2022-07-19 19:33 UTC, capsulated commented on internal/agent/agent.go
> +		os.Exit(1)
лучше error возвращать, а закрывать программу в cmd/main

2022-07-19 19:33 UTC, capsulated commented on internal/agent/agent.go
> +	defer response.Body.Close()
а defer повыше, сразу после открытия, он для этого и defer

2022-07-19 19:33 UTC, capsulated commented on internal/repo/repo.go
> +type Repository interface {
**рекомендация**: интерфейс обычно в том же пакете описывают, где и реализация. Это отличия go с тем же C++ или TypeScript, где интерфейсы отдельными файлами/папками лежат. Связано с тем, что в **go** папки - это пакеты.

Примеры можно посмотреть в коде стандартных библиотек. 

Хотя код будет сложнее для навигации и чтения, подход с интерфейсами в отдельном месте вполне допустимый и структуру приложение можно построить таким образом, особенно если приложение большое, с множеством разных пакетов, где может использоваться интерфейс в разных пакетах, как С++ подобных больших проектах.

2022-07-19 19:33 UTC, capsulated commented on internal/storage/storage.go
> +func (s *storage) GetGauge(ctx context.Context, id string) (float64, error) {
Тут даже **context** на будущее добавлен? ) Это круто, можно будет потом заменить на основе интерфейса и добавить **ctx** в работу нового БД-Storage на основе этого интерфейса 🔥

2022-07-19 19:33 UTC, capsulated commented on cmd/agent/main.go
> +	agent := agent.NewAgent(nil)
А nil в параметр можно не передавать, он и так для указателя будет nil при вызове agent.NewAgent()

2022-07-19 19:33 UTC, capsulated commented on internal/repo/repo.go
> +type Repository interface {
И в go обычно называют с постфиксом -er. 
https://go.dev/doc/effective_go#interface-names

Что-то типа Storager. 

Но в нашем случае - по желанию. Так как это тоже правильно, но немного другой подход и на нём также можно построить хорошо читаемое, организованное приложение. В PHP было бы IStorage наверное 🤔

2022-07-19 19:33 UTC, capsulated commented on internal/storage/storage.go
> +	s.gauges[id] = value
Ещё бы мьютексы добавить. Но мы их, по-моему, ещё не проходили)

2022-08-03 01:22 UTC, alexander1389 commented on internal/storage/storage.go
> +	s.gauges[id] = value
Тут как раз ожидаю момента, когда по урокам дойдем до объектов синхронизации, поэтому пока оставлю так

2022-08-03 01:25 UTC, alexander1389 commented on cmd/agent/main.go
> +	agent := agent.NewAgent(nil)
Так не получается, ругается на `./main.go:10:7: not enough arguments in call to agent.NewAgent`

2022-08-03 01:26 UTC, alexander1389 commented on internal/agent/agent.go
> +	defer response.Body.Close()
Если перенести выше, то ворнинг появляется `using response before checking for errors`

2022-08-03 01:37 UTC, merged